version: "3.1"
services: 
    db: 
        image: postgres:13 
        container_name: db_a11 
        environment: 
            - POSTGRES_DB=postgres 
            - POSTGRES_PASSWORD=pass_postgres 
            - POSTGRES_USER=user_postgres 
        ports: 
            - "5433:5432"
        volumes: 
            - local_pgdata:/var/lib/postgresql/data
    pgadmin: 
        image: dpage/pgadmin4
        container_name: pg_a11
        ports: 
            - "81:80" 
        environment: 
            - PGADMIN_DEFAULT_EMAIL=roger.sobrino@xtec.cat 
            - PGADMIN_DEFAULT_PASSWORD=roger123
        volumes: 
            - pgadmin-data:/var/lib/pgadmin 
volumes: 
    local_pgdata: 
    pgadmin-data: